---
- name: Download node_exporter and install
  hosts: ec2_test
  become: yes
  gather_facts: no
  vars:
    node_exporter_pkg_url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    node_exporter_folder: node_exporter-1.3.1.linux-amd64
    node_exporter_dest: /tmp/
    node_exporter_bin_dir: /usr/local/bin/
    node_exporter_service_dir: /etc/systemd/system/node_exporter.service
    node_exporter_user: node_exporter
    node_exporter_group: node_exporter
    node_exporter_executable: /usr/local/bin/node_exporter

  tasks:
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      creates: '{{node_exporter_dest}}{{node_exporter_folder}}'
      src: '{{ node_exporter_pkg_url }}'
      dest: '{{ node_exporter_dest }}'
      remote_src: yes
  - name: create a node_exporter user
    user:
      name: '{{node_exporter_user}}'
      shell: /bin/false
  - name: Move node_exporter to bin dir
    copy:
      src: '{{node_exporter_dest}}{{node_exporter_folder}}/node_exporter'
      dest: '{{node_exporter_bin_dir}}'
      remote_src: yes
      group: '{{node_exporter_group}}'
      mode: '0774'
  - name: Template a file to /etc/systemd/system/node_exporter.service
    ansible.builtin.template:
      src: node_exporter.service.j2
      dest: '{{node_exporter_service_dir}}'
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      daemon_reload: yes
      name: node_exporter
      enabled: yes
