- job_name: node_exporter
  static_configs:
  - targets:  
    - '3.12.163.141:9100'
# - job_name: blackbox
#   metrics_path: /probe
#   params:
#     module: [http_prometheus] 
#   static_configs:
#     - targets:
#       - https://www.facebook.com/    # Target to probe with https.
#       - https://www.linkedin.com/feed/
#       - https://www.azercell.com/az/
#   relabel_configs:
#     - source_labels: [__address__]
#       target_label: __param_target
#     - source_labels: [__param_target]
#       target_label: instance
#     - target_label: __address__
#       replacement:  prometheus-blackbox-prometheus-blackbox-exporter.monitoring:9115 # The blackbox exporter's real hostname:port.